version: '3'
services:
  api:
    build:
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5432:5432'
